Better UI for command execution; Fix some templates;

diff --git a/root/usr/local/bin/kubeconfig-get b/root/usr/local/bin/kubeconfig-get
--- a/root/usr/local/bin/kubeconfig-get
+++ b/root/usr/local/bin/kubeconfig-get
@@ -8,48 +8,63 @@ if [ -v KUBECONFIG ]; then
     debug Using KUBECONFIG=$KUBECONFIG
 fi
 
-if [ $# -gt 0 ]; then
-    cluster_type=$1
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -n|--cluster-name)
+            shift
+            cluster_name=$1
+        ;;
+        -t|--cluster-type)
+            shift
+            cluster_type=$1
+        ;;
+        -f|--force)
+            read_config=":"
+    esac
     shift
-fi
-
-if [ $# -gt 0 ]; then
-    cluster_name=$1
-    shift
-fi
+done
 
 info Retrieving kubeconfig for $cluster_name/$cluster_type
 
 case $cluster_type in
     kind)
-        exec kind export kubeconfig --name $cluster_name "$@"
+        execute_command kind export kubeconfig --name $cluster_name "$@"
     ;;
 
     eks)
-        exec aws eks update-kubeconfig --name $cluster_name "$@"
+        export AWS_ACCESS_KEY_ID=$(get_tf_config AWS_ACCESS_KEY_ID aws_access_key_id)
+        export AWS_SECRET_ACCESS_KEY=$(get_tf_config AWS_SECRET_ACCESS_KEY aws_secret_access_key)
+        export AWS_DEFAULT_REGION=$(get_tf_config AWS_DEFAULT_REGION region)
+
+        [ -n "$AWS_ACCESS_KEY_ID " ] || read_config AWS_ACCESS_KEY_ID 'AWS Access Key ID'
+        [ -n "$AWS_SECRET_ACCESS_KEY" ] || _secret=true read_config AWS_SECRET_ACCESS_KEY 'AWS Secret Access Key'
+        [ -n "$AWS_DEFAULT_REGION" ] || read_config AWS_DEFAULT_REGION 'AWS Default Region'
+
+        execute_command aws eks update-kubeconfig --name $cluster_name "$@"
     ;;
 
     doks)
         if ! [ -e ~/.config/doctl/config.yaml ]; then
-            doctl auth init
+            execute_command doctl auth init
         fi
-        exec doctl kubernetes cluster kubeconfig save ${cluster_name}
+        execute_command doctl kubernetes cluster kubeconfig save ${cluster_name}
     ;;
 
     gke)
-        if [ -e "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
-            gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
-            read_config GCP_PROJECT "GCP Project"
-            gcloud config set project $GCP_PROJECT
-            read_config GCE_ZONE "GCE Zone"
-            gcloud container clusters get-credentials --zone $GCE_ZONE --project $GCP_PROJECT $cluster_name
-        else 
-            read_config GCP_PROJECT "GCP Project"
-            gcloud config set project $GCP_PROJECT
+        export GCP_PROJECT=$(get_tf_config GCP_PROJECT project_id)
+        export GCE_ZONE=$(get_tf_config GCE_ZONE zones | head -1)
 
-            read_config GCE_ZONE "GCE Zone"
-            gcloud container clusters get-credentials --zone $GCE_ZONE --project $GCP_PROJECT $cluster_name
+        [ -n "$GCP_PROJECT" ] || read_config GCP_PROJECT "GCP Project"
+        [ -n "$GCE_ZONE" ] || read_config GCE_ZONE "GCE Zone"
+
+        if [ -e "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
+            execute_command gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
+        else
+            warn "Missing service account file $GOOGLE_APPLICATION_CREDENTIALS (\$GOOGLE_APPLICATION_CREDENTIALS)"
         fi
+
+        execute_command gcloud config set project $GCP_PROJECT
+        execute_command gcloud container clusters get-credentials --zone $GCE_ZONE --project $GCP_PROJECT $cluster_name
     ;;
 
     oke)
@@ -82,7 +97,7 @@ case $cluster_type in
             oci ce cluster list --compartment-id $OCI_COMPARTMENT_ID --all --output table --query 'data[].name'
         done
         OCI_CLUSTER_ID=$(oci ce cluster list --name $OCI_CLUSTER_NAME --compartment-id $OCI_COMPARTMENT_ID | jq -r '.data[0].id')
-        oci ce cluster create-kubeconfig --cluster-id $OCI_CLUSTER_ID \
+        execute_command oci ce cluster create-kubeconfig --cluster-id $OCI_CLUSTER_ID \
             --file $CLUSTER_DIR/.kube/config --region $OCI_CLI_REGION \
             --token-version 2.0.0
     ;;
@@ -98,20 +113,33 @@ case $cluster_type in
     ;;
 
     aks)
-        export ARM_CLIENT_ID=$(sed -ne 's/^client_id.*"\([^"]\+\)"/\1/p' /cluster/terraform.tfvars)
-        export ARM_CLIENT_SECRET=$(sed -ne 's/^client_secret.*"\([^"]\+\)"/\1/p' /cluster/terraform.tfvars)
-        export ARM_TENANT_ID=$(sed -ne 's/^tenant_id.*"\([^"]\+\)"/\1/p' /cluster/terraform.tfvars)
-        export ARM_SUBSCRIPTION_ID=$(sed -ne 's/^subscription_id.*"\([^"]\+\)"/\1/p' /cluster/terraform.tfvars)
-        export AKS_RESOURCE_GROUP_NAME=$(sed -ne 's/^resource_group_name.*"\([^"]\+\)"/\1/p' /cluster/terraform.tfvars)
+        export ARM_CLIENT_ID=$(get_tf_config ARM_CLIENT_DIR client_id)
+        export ARM_CLIENT_SECRET=$(get_tf_config ARM_CLIENT_SECRET client_secret)
+        export ARM_TENANT_ID=$(get_tf_config ARM_TENANT_ID tenant_id)
+        export ARM_SUBSCRIPTION_ID=$(get_tf_config ARM_SUBSCRIPTION_ID subscription_id)
+        export AKS_RESOURCE_GROUP_NAME=$(get_tf_config AKS_RESOURCE_GROUP_NAME resource_group_name)
 
-        read_config ARM_CLIENT_ID "ARM_CLIENT_ID"
-        read_config ARM_CLIENT_SECRET "ARM_CLIENT_SECRET"
-        read_config ARM_TENANT_ID "ARM_TENANT_ID"
-        read_config ARM_SUBSCRIPTION_ID "AKS Subscription ID"
-        read_config AKS_RESOURCE_GROUP_NAME "AKS Resource Group Name"
+        [ -n "$ARM_CLIENT_ID" ] || read_config ARM_CLIENT_ID 'ARM Client ID'
+        [ -n "$ARM_CLIENT_SECRET" ] || _secret=true read_config ARM_CLIENT_SECRET 'ARM Client Secret'
+        [ -n "$ARM_TENANT_ID" ] || read_config ARM_TENANT_ID 'ARM Tenant ID'
+        [ -n "$ARM_SUBSCRIPTION_ID" ] || read_config ARM_SUBSCRIPTION_ID 'AKS Subscription ID'
+        [ -n "$AKS_RESOURCE_GROUP_NAME" ] || read_config AKS_RESOURCE_GROUP_NAME 'AKS Resource Group Name'
 
-        ask_execute_command az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET -t $ARM_TENANT_ID
-        az aks get-credentials --admin --name $cluster_name --resource-group $AKS_RESOURCE_GROUP_NAME --subscription $ARM_SUBSCRIPTION_ID
+        _print_cmd="az login --service-principal -u $ARM_CLIENT_ID -p <SECRET> -t $ARM_TENANT_ID" \
+            execute_command \
+                az login --service-principal \
+                    -u $ARM_CLIENT_ID \
+                    -p $ARM_CLIENT_SECRET \
+                    -t $ARM_TENANT_ID \
+            || exit
+
+        execute_command \
+            az aks get-credentials \
+                --admin \
+                --name $cluster_name \
+                --resource-group $AKS_RESOURCE_GROUP_NAME \
+                --subscription $ARM_SUBSCRIPTION_ID \
+                --overwrite-existing
     ;;
 
     *)
